// client/src/pages/recommend/ByList.tsx
import React, { useEffect, useState } from 'react';
import Navbar from '../../components/Navbar';
import SVG from '../../components/SVG';
import { importAnimeList } from '../../utils/importAnimeList';
import { OAuth } from '../../utils/OAuth';
import RecommendationGrid from '../../components/RecommendationGrid';

const ByList: React.FC = () => {
    const [isLoaded, setIsLoaded] = useState(false);
    const [isLoggedIn, setIsLoggedIn] = useState(false);
    const [loginType, setLoginType] = useState('none');
    const [accessToken, setAccessToken] = useState('');

    const [isImporting, setIsImporting] = useState(false);
    const [importSuccess, setImportSuccess] = useState(false);
    const [importError, setImportError] = useState('');
    const [importedData, setImportedData] = useState<any>(null);

    const [isRecommending, setIsRecommending] = useState(false);
    const [recommendations, setRecommendations] = useState<any[] | null>(null);
    const [excludeWatched, setExcludeWatched] = useState(true);
    const [recommendError, setRecommendError] = useState('');

    const handleListImport = async () => {
        if (!isLoggedIn) {
            setImportError("You need to be logged in to import your anime list.");
            return;
        }

        setIsImporting(true);
        setImportError("");
        setImportSuccess(false);

        try {
            const data = await importAnimeList(loginType, accessToken);
            setImportedData(data);
            setImportSuccess(true);
        } catch (error) {
            console.error("Error importing anime list:", error);
            setImportError("Failed to import anime list. Please try again.");
        } finally {
            setIsImporting(false);
        }
    };

    const handleRecommend = async () => {
        setIsRecommending(true);
        setRecommendError("");
        try {
            const res = await fetch('/api/recommend', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ importedData, excludeWatched })
            });
            
            if (!res.ok) {
                throw new Error("Failed to get recommendations");
            }
            
            const data = await res.json();
            setRecommendations(data);
        } catch (error) {
            console.error(error);
            setRecommendError("Failed to fetch recommendations. Please try again.");
        } finally {
            setIsRecommending(false);
        }
    };

    const logout = async () => {
        await fetch('/auth/logout', { method: 'POST' });
        setIsLoggedIn(false);
        setLoginType('none');
        setImportSuccess(false);
        setImportedData(null);
        setRecommendations(null);
    };

    const syntaxHighlightJson = (json: string): string => {
        if (!json) return "";
        return json.replace(
            /("(\\u[a-zA-Z0-9]{4}|\\[^u]|[^\\"])*"(?:\s*:)?|\b(true|false|null)\b|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)/g,
            (match: string): string => {
                let cls = "text-white"; // default
                if (/^"/.test(match)) {
                    if (/:$/.test(match)) {
                        cls = "text-yellow-400"; // key
                    } else {
                        cls = "text-green-400"; // string
                    }
                } else if (/true|false/.test(match)) {
                    cls = "text-blue-400"; // booleans
                } else if (/null/.test(match)) {
                    cls = "text-gray-400"; // null
                } else {
                    cls = "text-purple-400"; // numbers
                }
                return `<span class="${cls}">${match}</span>`;
            }
        );
    };

    useEffect(() => {
        const fetchStatus = async () => {
            const status = await fetch('/auth/status', { credentials: 'include' });
            const { isLoggedIn: logged, accessToken: token, loginType: type } = await status.json();

            setIsLoggedIn(logged);
            setLoginType(type);
            setAccessToken(token || "");

            // Preload images trick from original code
            const imagesToLoad = Array.from(document.images)
                .filter(img => !img.complete)
                .map(img => new Promise(resolve => {
                    img.onload = img.onerror = resolve;
                }));
            await Promise.all(imagesToLoad);
            
            setTimeout(() => {
                setIsLoaded(true);
            }, 100);
        };

        fetchStatus();
    }, []);

    return (
        <div className="min-h-screen bg-gradient-to-br from-[#090311] to-[#141634] text-white bg-fixed">
            <Navbar color="#a78bfa" />

            <section className="bg-transparent relative text-white overflow-hidden">
                <div className="relative z-10 flex flex-col-reverse lg:flex-row items-center justify-between px-6 sm:px-10 lg:px-27 pt-24 lg:pt-36 pb-5 gap-1">
                    
                    <div className={`text-left w-full max-w-3xl transition-opacity duration-500 ${isLoaded ? 'animate-fade-in-top opacity-100' : 'opacity-0'}`}>
                        <h1 className="text-4xl sm:text-5xl font-extrabold leading-tight mb-6">
                            <span className="text-purple-300 text-3xl sm:text-4xl font-black font-newtegomin">
                                Recommendation using your lists
                            </span>
                        </h1>

                        <p className="text-white/70 text-lg sm:text-lg mb-6 font-mono leading-relaxed">
                            Import your anime lists from AniList or MyAnimeList to receive personalized recommendations based on the genres you watch most, how you've rated them, and more. 
                        </p>

                        {/* Login status */}
                        {isLoggedIn ? (
                            <>
                                <div className="flex items-center mb-4 text-green-400 font-mono gap-2">
                                    <SVG name="checkmark" size="w-5 h-5" />
                                    <span>You are already logged in via</span>
                                    {loginType === "AniList" ? (
                                        <SVG name="anilist" size="w-4.5 h-4.5" />
                                    ) : loginType === "MyAnimeList" ? (
                                        <SVG name="mal" size="w-8 h-8" />
                                    ) : null}
                                </div>
                                <div className="flex flex-row gap-3">
                                    {!importSuccess ? (
                                        <button 
                                            onClick={handleListImport} 
                                            className="px-4 py-[8.5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2"
                                            disabled={isImporting}
                                        >
                                            {isImporting ? (
                                                <>
                                                    <SVG name="loader" size="w-5 h-5" className="animate-spin" />
                                                    Importing...
                                                </>
                                            ) : (
                                                <>
                                                    <SVG name="import" size="w-5 h-5" />
                                                    Import Lists
                                                </>
                                            )}
                                        </button>
                                    ) : (
                                        <div className="flex items-center gap-3">
                                            <button 
                                                onClick={handleRecommend}
                                                disabled={isRecommending}
                                                className="px-4 py-[8.5px] bg-green-400/30 hover:bg-green-400/40 rounded-lg text-white font-mono flex items-center gap-2"
                                            >
                                                {isRecommending ? (
                                                    <>
                                                        <SVG name="loader" size="w-5 h-5" className="animate-spin" />
                                                        Generating...
                                                    </>
                                                ) : (
                                                    <>
                                                        <SVG name="star" size="w-5 h-5" />
                                                        Recommend
                                                    </>
                                                )}
                                            </button>
                                            <label className="flex items-center gap-2 font-mono text-sm text-gray-300 cursor-pointer">
                                                <input 
                                                    type="checkbox" 
                                                    checked={excludeWatched} 
                                                    onChange={(e) => setExcludeWatched(e.target.checked)} 
                                                    className="accent-purple-400 w-4 h-4 rounded"
                                                />
                                                Exclude watched
                                            </label>
                                        </div>
                                    )}
                                    <button onClick={logout} className="px-4 py-[8.5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2" >
                                        <SVG name="logout" size="w-5 h-5" />
                                        Logout
                                    </button>
                                </div>
                                {importError && <p className="mt-3 text-red-400 font-mono">{importError}</p>}
                                {importSuccess && importedData && (
                                    <div className="mt-3 p-3 bg-white/10 rounded-lg font-mono text-sm max-h-[150px] overflow-y-auto text-white overflow-x-auto">
                                        <p className="mb-2 text-green-400">Imported Lists:</p>
                                        <p className="mb-2 text-green-400"> - Anime completed: {importedData.completed.length}</p>
                                        <p className="mb-2 text-green-400"> - Anime watching: {importedData.current.length}</p>
                                        <p className="mb-2 text-green-400"> - Anime planned: {importedData.planning.length}</p>
                                        <pre className="whitespace-pre-wrap break-all" dangerouslySetInnerHTML={{ __html: syntaxHighlightJson(JSON.stringify(importedData, null, 2)) }}></pre>
                                    </div>
                                )}
                                {recommendError && <p className="mt-3 text-red-400 font-mono">{recommendError}</p>}
                                {recommendations && (
                                    <div className="mt-8 w-full">
                                        <h2 className="text-2xl font-bold font-mono mb-4 text-purple-300">Your Recommendations</h2>
                                        <RecommendationGrid recommendations={recommendations} />
                                    </div>
                                )}
                            </>
                        ) : (
                            <>
                                <div className="flex items-center mb-4 text-red-400 font-mono">
                                    <SVG name="cross" size="w-5 h-5" />
                                    <span className="ml-2">You are not logged in</span>
                                </div>
                                <div className="flex flex-row gap-3">
                                    <button onClick={() => OAuth("AniList")} className="px-4 py-[5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2">
                                        Connect with <SVG name="anilist" size="w-4.5 h-4.5" />
                                    </button>
                                    <button onClick={() => OAuth("MyAnimeList")} className="px-4 py-[5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2">
                                        Connect with <SVG name="mal" size="w-8 h-8" />
                                    </button>
                                </div>
                            </>
                        )}
                    </div>
                    
                    {!importSuccess && !importedData && !recommendations && (
                        <div className="flex-shrink-0">
                            {/* Mobile image */}
                            <img
                                src="/img2.png"
                                alt="img2"
                                className={`block lg:hidden w-[350px] sm:w-[350px] lg:w-[320px] h-auto drop-shadow-2xl rounded-lg transition-opacity duration-500 mb-3 ${isLoaded ? 'animate-fade-in-top opacity-100' : 'opacity-0'}`}
                            />
                            {/* Desktop image */}
                            <img
                                src="/img3.png"
                                alt="img3"
                                className={`hidden lg:block w-[260px] sm:w-[300px] lg:w-[320px] h-auto drop-shadow-2xl rounded-lg transition-opacity duration-500 ml-3 ${isLoaded ? 'animate-fade-in-bottom opacity-100' : 'opacity-0'}`}
                            />
                        </div>
                    )}
                </div>
            </section>
        </div>
    );
};

export default ByList;

// src/routes/recommend/by-list/+page.svelte
<script lang="ts">
    import { onMount } from "svelte";
    import SVG from "$lib/components/SVG.svelte";
    import Navbar from "$lib/components/Navbar.svelte";
    import { importAnimeList } from '$lib/utils/importAnimeList';
    import { OAuth } from "$lib/utils/OAuth";
    import Cookies from "js-cookie";

    let isLoaded = false;
    let isLoggedIn = false;
    let loginType = "none";
    let accessToken = "";

    async function handleListImport() {
        if (!isLoggedIn) {
            alert("You need to be logged in to import your anime list.");
            return;
        }

        importAnimeList(loginType, accessToken)
            .then(data => {
                console.log("Anime list imported successfully:", JSON.stringify(data));
                alert("Anime list imported successfully!");
            })
            .catch(error => {
                console.error("Error importing anime list:", error);
                alert("Failed to import anime list. Please try again.");
            });
    }

    async function logout() {
        await fetch('/auth/logout', { method: 'POST' });
        isLoggedIn = false;
        loginType = 'none';
    }

    onMount(async () => {
        const status = await fetch('/auth/status', { credentials: 'include' });
        const { isLoggedIn: logged, accessToken: token, loginType: type } = await status.json();

        isLoggedIn = logged;
        loginType = type;
        accessToken = token || "";

        const imagesToLoad = Array.from(document.images)
            .filter(img => !img.complete)
            .map(img => new Promise(resolve => {
                img.onload = img.onerror = resolve;
            }));

        await Promise.all(imagesToLoad);

        await new Promise(r => setTimeout(r, 100));

        isLoaded = true;
    });
</script>

<Navbar color="#a78bfa"/>

<section class="min-h-screen bg-gradient-to-br from-[#090311] to-[#141634] relative text-white overflow-hidden">
    <div class="relative z-10 flex flex-col-reverse lg:flex-row items-center justify-between px-6 sm:px-10 lg:px-27 pt-24 lg:pt-36 pb-5 gap-1">
        
        <div class="text-left w-full max-w-3xl {isLoaded ? 'animate-fade-in-top' : 'opacity-0'}">
            <h1 class="text-4xl sm:text-5xl font-extrabold leading-tight mb-6">
                <span class="text-purple-300 text-3xl sm:text-4xl font-black font-newtegomin">
                    Recommendation using your lists
                </span>
            </h1>

            <p class="text-white/70 text-lg sm:text-lg mb-6 font-mono leading-relaxed">
                Import your anime lists from AniList or MyAnimeList to receive personalized recommendations based on the genres you watch most, how you've rated them, and more. 
            </p>

            <!-- Login status -->
            {#if isLoggedIn}
                <div class="flex items-center mb-4 text-green-400 font-mono gap-2">
                <!-- Checkmark Icon -->
                    <SVG name="checkmark" size="w-5 h-5" />
                    
                    <span>You are already logged in via</span>

                    {#if loginType === "AniList"}
                        <SVG name="anilist" size="w-4.5 h-4.5" />
                    {:else if loginType === "MyAnimeList"}
                        <SVG name="mal" size="w-8 h-8" />
                    {/if}
                </div>
                <div class="flex flex-row gap-3">
                    <button on:click={handleListImport} class="px-4 py-[8.5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2" >
                        <!-- Import Icon -->
                        <SVG name="import" size="w-5 h-5" />
                        Import Lists
                    </button>
                    <button on:click={logout} class="px-4 py-[8.5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2" >
                        <SVG name="logout" size="w-5 h-5" />
                        Logout
                    </button>
                </div>
            {:else}
                <div class="flex items-center mb-4 text-red-400 font-mono">
                    <!-- Cross Icon -->
                    <SVG name="cross" size="w-5 h-5" />
                    <span class="ml-2">You are not logged in</span>
                </div>
                <div class="flex flex-row gap-3">
                    <button on:click={() => OAuth("AniList")} class="px-4 py-[5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2">
                        Connect with
                        <SVG name="anilist" size="w-4.5 h-4.5" />
                    </button>
                    <button on:click={() => OAuth("MyAnimeList")} class="px-4 py-[5px] bg-purple-400/30 hover:bg-purple-400/40 rounded-lg text-white font-mono flex items-center gap-2">
                        Connect with
                        <SVG name="mal" size="w-8 h-8" />
                    </button>
                </div>
            {/if}
        </div>
        
        <!-- Image -->
        <div class="flex-shrink-0">
            <!-- Mobile image -->
            <img
                src="/img2.png"
                alt="img2"
                class="block lg:hidden w-[350px] sm:w-[350px] lg:w-[320px] h-auto drop-shadow-2xl rounded-lg {isLoaded ? 'animate-fade-in-top' : 'opacity-0'} mb-3"
            />

            <!-- Desktop image -->
            <img
                src="/img3.png"
                alt="img3"
                class="hidden lg:block w-[260px] sm:w-[300px] lg:w-[320px] h-auto drop-shadow-2xl rounded-lg {isLoaded ? 'animate-fade-in-bottom' : 'opacity-0'} ml-3"
            />
        </div>
    
    </div>
</section>

<style>
    @keyframes fade-in-bottom {
        from {
            opacity: 0;
            transform: translateY(20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }
    @keyframes fade-in-top {
        from {
            opacity: 0;
            transform: translateY(-20px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .animate-fade-in-top {
        animation: fade-in-top 500ms ease-out;
    }
    .animate-fade-in-bottom {
        animation: fade-in-bottom 500ms ease-out;
    }
</style>
